<?php

namespace Nucleus\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaieRepository extends EntityRepository
{
}
