<?php

namespace Nucleus\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends EntityRepository
{
    public function findCountAllReponse()
    {
        return $this->getEntityManager()
        ->createQuery(
        'SELECT COUNT(p) FROM NucleusHomeBundle:Reponse p'
        )->getScalarResult();
    }
}
