services:
    sonata.admin.departement:
        class: Nucleus\HomeBundle\Admin\DepartementAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Departement" }
        arguments:
            - ~
            - Nucleus\HomeBundle\Entity\Departement
            - ~
        calls:
           # - [ setTranslationDomain, [NucleusHomeBundle]]