parameters:
#    nucleus_home.example.class: Nucleus\HomeBundle\Example

services:
#    nucleus_home.example:
#        class: %nucleus_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
